### ISSUE TITLE
coordinate transformation 

### ISSUE THREAD

**Issue by Grandzxw** [lifelong-robotic-vision/lifelong-slam#13]
Do the coordinates of the wheel odometer represent the base_link coordinates?

**Comment by cedrusx** [comment]
Yes they do

**Comment by Grandzxw** [comment]
One more question: Can the angular and linear velocity integrals of a wheel directly get the wheel's pose? or the IMU data needs to be added？

**Comment by cedrusx** [comment]
> One more question: Can the angular and linear velocity integrals of a wheel directly get the wheel's pose? or the IMU data needs to be added？

`base_link` poses have already been given in the odometry data (in the `base_odom` frame). No need to do any integration if you want a trajectory from wheel odemetry.

**Comment by Grandzxw** [comment]
Is the IMU data added to the wheel pose? If you're going to get a direct integral without IMU data, can you get a  pose?

**Comment by cedrusx** [comment]
> Is the IMU data added to the wheel pose? If you're going to get a direct integral without IMU data, can you get a pose?

For home/cafe/office/corridor, the odometry data were fused from data from wheel encoders and an IMU on the base. For market, the odometry data were directly from wheel encoders.

**Comment by cedrusx** [comment]
closing as no update for months - feel free to re-open
