### ISSUE TITLE
Use Bag files with Realsense SDK

### ISSUE THREAD

**Issue by upasana27** [lifelong-robotic-vision/lifelong-slam#16]
How can we use the data obtained from these bag files for processing using the librealsense library?

**Comment by cedrusx** [comment]
Hi @upasana27 , in order to proceed with librealsense, you need to download the `rosbag-raw` data listed near the end of the index doc. You can then launch those bags either with `realsense_ros` or the librealsense API.

May I know about the reason to use librealsense? Thanks.

**Comment by upasana27** [comment]
HI @cedrusx Thanks! It works perfectly. Closing the issue since it is solved.

Regards
